### ISSUE TITLE
Cassandra Maven Plugin 3.6 not working with Spring Boot 2.0.0.RC1

### ISSUE THREAD

**Issue by indrabasak** [mojohaus/cassandra-maven-plugin#23]
Cassandra Maven Plugin version 3.6 is not working with Spring Boot 2.0.0.RC1. Spring Boot is dependent on 3.4.0 version of Datastax's Cassandra driver.  Here is the exception I am getting,

```
Error creating bean with name 'session' defined in class path resource [com/basaki/service/config/CassandraConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.driver.core.Session]: Factory method 'testSession' threw exception; nested exception is java.lang.IllegalStateException: Can't use this cluster instance because it was previously closed
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:729)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:192)
```

**Comment by indrabasak** [comment]
It works with Spring Boot 2.0.0.RELEASE.
