### ISSUE TITLE
java.lang.NullPointerException at org.codehaus.mojo.cassandra.CqlExecCassandraMojo.printResults(CqlExecCassandraMojo.java:99) 

### ISSUE THREAD

**Issue by khaing211** [mojohaus/cassandra-maven-plugin#8]
Cassandra-maven-plugin: version: 2.1.7-1

Stack trace:

```
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution create-cassandra-schema of goal org.codehaus.mojo:cassandra-maven-plugin:2.1.7-1:cql-exec failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: java.lang.NullPointerException
    at org.codehaus.mojo.cassandra.CqlExecCassandraMojo.printResults(CqlExecCassandraMojo.java:99)
    at org.codehaus.mojo.cassandra.CqlExecCassandraMojo.execute(CqlExecCassandraMojo.java:87)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
```

Cql script:

```
CREATE KEYSPACE xxxx WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 } AND DURABLE_WRITES = true ;

CREATE TABLE xxxx.yyyy (
  id uuid,
  PRIMARY KEY (id)
);
```

**Comment by khaing211** [comment]
Sorry I forgot

Maven configuration

```
                    <execution>
                        <id>create-cassandra-schema</id>
                        <goals>
                            <goal>cql-exec</goal>
                        </goals>
                        <phase>pre-integration-test</phase>
                        <configuration>
                            <cqlScript>${basedir}/src/test/resources/META-INF/cassandra/dataset/cassandra_dataset_example.cql</cqlScript>
                            <cqlVersion>3.0.0</cqlVersion>
                        </configuration>
                    </execution>
```

**Comment by wasyl77** [comment]
Same issue here. Any help ?

**Comment by Willem1987** [comment]
Same issue.

Plugin tries to print results as if all CQLResult returns are CqlResultType ROW.
There are 3 types:
  ROWS(1),
  VOID(2),
  INT(3);

Our create and drop table statements were type void. Thus result.getRows() delivers null. The CqlResult is in the thrift API and marks Fields as optional:
  public CqlResultType type; // required
  public List<CqlRow> rows; // optional
  public int num; // optional
  public CqlMetadata schema; // optional

Line 99 contains:
for (CqlRow row : result.getRows())

With result type VOID or INT getRows returns null causing a NullPointerException in the for-loop.

**Comment by olamy** [comment]
should be fixed with current snapshot.
can you have a try?

**Comment by Willem1987** [comment]
We are currently using a fork of this code with <cassandraVersion>2.1.7</cassandraVersion>. This is working for us.

**Comment by olamy** [comment]
fixed
